version: '3'

services:

  php:
      image: php:8.2-fpm-alpine
      container_name: php
      volumes:
        - ./src:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "7070:70"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/var/www/html
    command: ["nginx", "-g", "daemon off;"]

    depends_on:
      - php

  db:
    image: mariadb
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

    environment: 
      MA_VAR: "MA VALUE"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  phpMyAdmin:
    image: phpmyadmin
    container_name: phpMyAdmin

    environment: 
      PMA_HOST: "${PMA_HOST}"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASSWORD}"

    ports:
      - "6060:80"

  